name: timeside
channels:
  - conda-forge
  - yaafe
dependencies:
  - aubio  # in conda-forge channel (optionnal)
  - h5py
  - jupyter
  - matplotlib
  - mysql-python
  - networkx
  - numpy
  - pandas
  - pillow
  - python=2.7
  - pyyaml
  - redis
  - scipy
  - simplejson
  - pytables  # named tables in Pypi ...
  - traits
  - yaafe # in yaafe channel (optionnal)
  - Werkzeug
  - pip:
      - django-angular
      - django-bootstrap-pagination
      - django-bootstrap3
      - django-bower
      - celery==3.*
      - django-celery==3.1.17
      - django-debug-toolbar==1.3
      - django-environ
      - django-extensions
      - django==1.6.*
      - djangorestframework==2.*
      - mutagen
      - py_sonicvisualiser==0.2-9-gebe83bd
      - pympi-ling
      - south
      - uwsgi
      - watchdog
