name: app
channels:
- defaults
- conda-forge
dependencies:
- conda-forge::argtable2=2.13=0
- conda-forge::aubio=0.4.4=np112py27_7
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::backports_abc=0.5=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::bleach=1.5.0=py27_0
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::configparser=3.5.0=py27_0
- conda-forge::cycler=0.10.0=py27_0
- conda-forge::dbus=1.10.10=3
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::eigen=3.3.1=0
- conda-forge::entrypoints=0.2.2=py27_1
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::expat=2.1.0=2
- conda-forge::ffmpeg=2.8.6=4
- conda-forge::fftw=3.3.6=0
- conda-forge::fontconfig=2.12.1=4
- conda-forge::freetype=2.7=1
- conda-forge::functools32=3.2.3.2=py27_1
- conda-forge::gettext=0.19.7=1
- conda-forge::glib=2.51.4=0
- conda-forge::gmp=6.1.2=0
- conda-forge::gst-plugins-base=1.8.0=0
- conda-forge::gstreamer=1.8.0=1
- conda-forge::h5py=2.7.0=np112py27_0
- conda-forge::hdf5=1.8.17=10
- conda-forge::html5lib=0.999=py27_0
- conda-forge::icu=58.1=1
- conda-forge::ipykernel=4.6.0=py27_0
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::ipywidgets=6.0.0=py27_0
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::jsonschema=2.5.1=py27_0
- conda-forge::jupyter=1.0.0=py27_0
- conda-forge::jupyter_client=5.0.1=py27_0
- conda-forge::jupyter_console=5.1.0=py27_0
- conda-forge::jupyter_core=4.3.0=py27_0
- conda-forge::lapack=3.6.1=1
- conda-forge::libffi=3.2.1=3
- conda-forge::libflac=1.3.1=0
- conda-forge::libiconv=1.14=4
- conda-forge::libogg=1.3.2=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libsndfile=1.0.27=1
- conda-forge::libsodium=1.0.10=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::libvorbis=1.3.5=0
- conda-forge::libxcb=1.12=1
- conda-forge::libxml2=2.9.4=4
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::matplotlib=2.0.0=np112py27_3
- conda-forge::mistune=0.7.4=py27_0
- conda-forge::mpg123=1.24.0=0
- conda-forge::nbconvert=5.1.1=py27_1
- conda-forge::nbformat=4.2.0=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::networkx=1.11=py27_0
- conda-forge::notebook=5.0.0=py27_0
- conda-forge::numexpr=2.6.2=np112py27_0
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::olefile=0.44=py27_0
- conda-forge::openblas=0.2.19=1
- conda-forge::openssl=1.0.2h=3
- conda-forge::pandas=0.19.2=np112py27_1
- conda-forge::pandoc=1.19.2=0
- conda-forge::pandocfilters=1.4.1=py27_0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pcre=8.39=0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pillow=4.0.0=py27_2
- conda-forge::pip=9.0.1=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::pyparsing=2.2.0=py27_0
- conda-forge::pyqt=5.6.0=py27_0
- conda-forge::pytables=3.3.0=np112py27_0
- conda-forge::python=2.7.13=0
- conda-forge::python-dateutil=2.6.0=py27_0
- conda-forge::pytz=2016.10=py27_0
- conda-forge::pyyaml=3.12=py27_1
- conda-forge::pyzmq=16.0.2=py27_1
- conda-forge::qt=5.6.2=1
- conda-forge::qtconsole=4.3.0=py27_0
- conda-forge::readline=6.2=0
- conda-forge::scandir=1.5=py27_1
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::sip=4.18=py27_1
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_1
- conda-forge::subprocess32=3.2.7=py27_0
- conda-forge::terminado=0.6=py27_0
- conda-forge::testpath=0.3=py27_0
- conda-forge::tk=8.5.19=1
- conda-forge::tornado=4.4.3=py27_0
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::traits=4.6.0=py27_1
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::webencodings=0.5=py27_0
- conda-forge::werkzeug=0.11.10=py27_0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::widgetsnbextension=2.0.0=py27_0
- conda-forge::x264=20131217=1
- conda-forge::xorg-libxau=1.0.8=3
- conda-forge::xorg-libxdmcp=1.1.2=3
- conda-forge::xz=5.2.2=0
- conda-forge::yaafe=0.70=py27_0
- conda-forge::yaml=0.1.6=0
- conda-forge::zeromq=4.2.1=1
- conda-forge::zlib=1.2.11=0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- mysql-python=1.2.5=py27_0
- redis=3.2.0=0
- simplejson=3.10.0=py27_0
- pip:
  - amqp==1.4.9
  - anyjson==0.3.3
  - argh==0.26.2
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - billiard==3.3.0.23
  - celery==3.1.25
  - django==1.6.11
  - django-angular==0.8.4
  - django-bootstrap-pagination==1.6.2
  - django-bootstrap3==8.2.2
  - django-bower==5.2.0
  - django-celery==3.1.17
  - django-debug-toolbar==1.3.0
  - django-environ==0.4.1
  - django-extensions==1.7.8
  - djangorestframework==2.4.8
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - kombu==3.0.37
  - mutagen==1.37
  - pathtools==0.1.2
  - prompt-toolkit==1.0.14
  - py-sonicvisualiser==0.2-9-gebe83bd
  - pympi-ling==1.69
  - south==1.0.2
  - sqlparse==0.2.3
  - tables==3.3.0
  - uwsgi==2.0.15
  - watchdog==0.8.3
